### List Orders
GET http://localhost:3001/orders HTTP/1.1

### List Canceled orders
GET http://localhost:3001/orders/canceled HTTP/1.1

### Create Order
POST http://localhost:3001/orders HTTP/1.1
content-type: application/json

{
	"clientId": 1,
	"dueDate": "10-01-2020",
  "isCanceled": false,
	"products": [
		{
			"orderId": "",
			"productId": 1,
			"qnt": 1
		},
		{
			"orderId": "",
			"productId": 2,
			"qnt": 1
		}
	]
}


### Delete Order/Cancel
DELETE http://localhost:3001/orders/7 HTTP/1.1



